# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoadmin', '0002_auto_20170613_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='mongoconnection',
            name='auth_database',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
